### ISSUE TITLE
Incompatibility with Python 3.14

### ISSUE THREAD

**Issue by ilovelinux** [encode/httpcore#1043]
Tested with `httpcore==1.0.9`

```python
Python 3.14.0rc3 (main, Sep 18 2025, 19:47:22) [Clang 20.1.4 ] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import httpcore
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import httpcore
  File "/lib/python3.14/site-packages/httpcore/__init__.py", line 140, in <module>
    setattr(__locals[__name], "__module__", "httpcore")  # noqa
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'typing.Union' object has no attribute '__module__' and no __dict__ for setting new attributes. Did you mean: '__reduce__'?
>>> 
```

**Comment by cclauss** [comment]
Python 3.14 (the π version) was released today.
* https://www.python.org/downloads/release/python-3140/
* https://github.com/actions/python-versions/releases

**Comment by GalaxySnail** [comment]
related to:
- https://github.com/python/cpython/issues/132139

**Comment by ilovelinux** [comment]
Apparently my environment was using an older version of httpcore (1.0.7).

In fact this issue has already been fixed with https://github.com/encode/httpcore/pull/1005, released in [v1.0.8](https://github.com/encode/httpcore/releases/tag/1.0.8).

I can confirm it works with Python 3.14rc3.

Duplicate of https://github.com/encode/httpcore/discussions/995
