### PR TITLE
Drop Python 3.6

### PR DESCRIPTION
**Pull request by michaeloliverx**
Closes: #515

### CODE REVIEW

**Comment by michaeloliverx** [comment]
Failing on an unrelated black/click error?

**Comment by florimondmanca** [comment]
@michaeloliverx Looks similar to this: https://github.com/encode/httpx/pull/2097#issuecomment-1082207141

**Comment by florimondmanca** [comment]
@michaeloliverx From #536 it looks like 3.6 CI is essentially broken because a bunch of core tooling have already dropped support. We might want to merge it into this PR so we don't try to upgrade tooling that wouldn't work on 3.6 anyway.

**Comment by tomchristie** [comment]
@florimondmanca - Make sense, yup. Is upgrading the pin on `black` and `twine` enough to resolve this particular pull request?

**Comment by michaeloliverx** [comment]
Okay were are stuck in the same place as https://github.com/encode/httpcore/pull/536 now.. If anyone has extra bandwidth feel free to add to this PR if not I can look again later.

**Comment by tomchristie** [comment]
Right, so we can either unpin `mkdocs`, or pin it to different versions depending on which Python version it's installed after.

**Comment by michaeloliverx** [comment]
Which 

> Right, so we can either unpin `mkdocs`, or pin it to different versions depending on which Python version it's installed after.

Unpinned `mkdocs` and now the `AttributeError: module 'jinja2' has no attribute 'contextfilter'` is back again. What Python versions should I be pinning it for ?

**Comment by florimondmanca** [comment]
@michaeloliverx I'm seeing something weird - mkdocs 1.2.4 (or 1.3.0) should have resolved the jinja2 issue but the one we're seeing (on jinja2==1.3.0 or 1.3.1) is different from the one reported and dealt with here: https://github.com/mkdocs/mkdocs/issues/2799

For now I'm attempting to pin jinja2 to 3.9.2 and see if it passes CI. Also pinning flake8 to a version before it pinned importlib-metadata on <3.8.

File: requirements.txt [hunk 1]
```diff
@@ -4,25 +4,26 @@
...
-black==22.1.0
+black==22.3.0
 coverage==6.2
-flake8==4.0.1
+flake8==3.9.2
 isort==5.10.1
 mypy==0.931
 pytest==7.0.1
-pytest-httpbin==1.0.1
+pytest-httpbin==1.0.2
```
Comment (graingert) [inline requirements.txt:27]:
```suggestion
pytest-httpbin==2.0.0rc1
```

Comment (florimondmanca) [reply requirements.txt:27]: Thanks! But the issue seems to be with httpbin itself. It imports `BaseResponse` but werkzeug==2.1.* released on March 28th removed it in favor of `Response`.

**Comment by michaeloliverx** [comment]
@florimondmanca I see green!

File: requirements.txt [hunk 2]
```diff
@@ -4,25 +4,27 @@
...
+wheel
 
 # Tests & Linting
 anyio==3.5.0
 autoflake==1.4
-black==22.1.0
+black==22.3.0
 coverage==6.2
-flake8==4.0.1
+flake8==3.9.2
```
Comment (florimondmanca) [inline requirements.txt:23]:
```suggestion
flake8==3.9.2  # See: https://github.com/PyCQA/flake8/pull/1438
```

**Comment by florimondmanca** [comment]
I'm happy to merge this, though the triple stitch on three different package compatibility issues is a bit disappointing. We can merge and review these when things settle down for either of the three cases... What do people think?

**Comment by michaeloliverx** [comment]
Added a note about 3.7+

**Review by florimondmanca — APPROVED** [review]

**Comment by florimondmanca** [comment]
Thanks so much @michaeloliverx. Approved the PR, feel free to merge whenever ready.
